### PR TITLE
ok?

### PR DESCRIPTION
**Pull request by JJorne-JDEVJ**

### CODE REVIEW

**Comment by wxnnvs** [comment]
can you fix https://github.com/wxnnvs/seb-win-bypass/commit/d7e8b0dd414ee1af23a578f46b453ca052aeb1df

**Comment by JJorne-JDEVJ** [comment]
il try

**Comment by JJorne-JDEVJ** [comment]
what r u trying to do?

**Comment by wxnnvs** [comment]
i got to go study now

**Pull request merged**
